[package]
name = "postgres_lsp"
version = "0.0.0"

edition.workspace = true

[dependencies]
lsp-server = "0.7.6"
lsp-types = { version = "=0.95.0", features = ["proposed"] }

serde_json = { workspace = true, features = ["preserve_order"] }
serde.workspace = true
anyhow.workspace = true
itertools.workspace = true

parser.workspace = true
stdx.workspace = true
tracing.workspace = true
vfs.workspace = true
