[package]
name = "codegen"
version = "0.0.0"

edition.workspace = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
pg_query_proto_parser.workspace = true

[lib]
proc-macro = true
doctest = false

